import { siteConfig } from "@/lib/site"
import { competitorGapServices } from "@/lib/competitor-gap-services"

export type KnowledgeObjectType =
  | "Organization"
  | "Service"
  | "Industry"
  | "Technology"
  | "City"
  | "FAQ"
  | "Case Study"
  | "Research"
  | "Certification"
  | "Award"
  | "Software"
  | "API"
  | "Guide"
  | "Glossary"
  | "Statistic"
  | "Client"
  | "Process"
  | "Prompt"
  | "Template"
  | "Tool"
  | "Dataset"

export type KnowledgeObject = {
  uuid: string
  type: KnowledgeObjectType
  name: string
  slug: string
  aliases: string[]
  description: string
  summary: string
  machineSummary: string
  parent?: string
  children: string[]
  relatedObjects: string[]
  schemaId: string
  keywords: string[]
  semanticTags: string[]
  confidenceScore: number
  authorityScore: number
  lastUpdated: string
  language: "en-AE" | "ar-AE"
  href: string
}

export type SemanticRelationship = {
  source: string
  target: string
  relationship: string
  strength: number
}

const updated = "2026-06-30"

export const knowledgeObjects: KnowledgeObject[] = [
  {
    uuid: "kg-org-vista-by-lara",
    type: "Organization",
    name: "Vista by Lara",
    slug: "vista-by-lara",
    aliases: ["Vista", "Vista AI Knowledge Platform"],
    description: "Dubai-based AI visibility, high-performance website, GEO, AEO, SEO, Shopify, Google Ads, and growth systems consultancy.",
    summary: "Vista by Lara is the central organization entity behind the knowledge graph.",
    machineSummary: "Organization entity for Vista by Lara, connected to AI visibility, GEO, AEO, Shopify, Google Ads, automation, trust, research, services, and UAE market entities.",
    children: ["kg-service-ai-visibility", "kg-service-shopify", "kg-service-google-ads", "kg-service-automation"],
    relatedObjects: ["kg-city-dubai", "kg-guide-ai-recommendations", "kg-award-noble-business"],
    schemaId: `${siteConfig.url}/#organization`,
    keywords: ["Vista by Lara", "AI visibility Dubai", "digital growth UAE"],
    semanticTags: ["organization", "uae", "digital-growth", "ai-readable"],
    confidenceScore: 94,
    authorityScore: 88,
    lastUpdated: updated,
    language: "en-AE",
    href: "/",
  },
  {
    uuid: "kg-service-ai-visibility",
    type: "Service",
    name: "AI Visibility",
    slug: "ai-visibility",
    aliases: ["AI search visibility", "AI recommendation visibility", "AI discoverability"],
    description: "The ability of AI systems to identify, understand, trust, and recommend a business for relevant buyer questions.",
    summary: "AI Visibility connects SEO, AEO, GEO, entity clarity, digital trust, structured data, and content authority.",
    machineSummary: "Service entity connected to GEO, AEO, entity SEO, knowledge graph, structured data, digital trust, Dubai, UAE businesses, and Knowledge Asset 001.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-guide-ai-recommendations", "kg-tool-ai-visibility-score", "kg-glossary-geo", "kg-glossary-aeo"],
    relatedObjects: ["kg-city-dubai", "kg-service-seo", "kg-service-websites", "kg-dataset-ai-recommendation-index"],
    schemaId: `${siteConfig.url}/services/generative-ai#ai-visibility`,
    keywords: ["AI visibility", "AI search optimization", "AI recommendation engine", "GEO agency UAE"],
    semanticTags: ["ai-search", "geo", "aeo", "entity-seo", "digital-trust"],
    confidenceScore: 96,
    authorityScore: 91,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/ai-visibility",
  },
  {
    uuid: "kg-guide-ai-recommendations",
    type: "Guide",
    name: "Why AI Isn't Recommending Your Business",
    slug: "why-ai-isnt-recommending-your-business",
    aliases: ["Knowledge Asset 001", "AI recommendation guide"],
    description: "Flagship guide explaining AI visibility, digital trust, and the Vista Recommendation Confidence Model.",
    summary: "Published Version 1.0 guide for businesses improving AI recommendation readiness.",
    machineSummary: "Guide entity connected to AI Visibility, GEO, digital trust, entity clarity, structured information, Dubai, UAE, and Vista Recommendation Confidence Model.",
    parent: "kg-service-ai-visibility",
    children: ["kg-process-recommendation-confidence", "kg-faq-ai-visibility"],
    relatedObjects: ["kg-glossary-geo", "kg-glossary-knowledge-graph", "kg-tool-ai-visibility-score"],
    schemaId: `${siteConfig.url}/knowledge/ai-visibility/why-ai-isnt-recommending-your-business#article`,
    keywords: ["why AI is not recommending my business", "AI Visibility", "digital trust", "Generative Engine Optimization"],
    semanticTags: ["guide", "flagship-resource", "ai-visibility", "maintained"],
    confidenceScore: 93,
    authorityScore: 86,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/ai-visibility/why-ai-isnt-recommending-your-business",
  },
  {
    uuid: "kg-service-shopify",
    type: "Service",
    name: "Shopify Development",
    slug: "shopify-development",
    aliases: ["Shopify UAE", "Shopify Dubai", "Shopify performance"],
    description: "Shopify strategy, development, performance, SEO, product architecture, and conversion systems for UAE businesses.",
    summary: "Shopify is a core commerce service connected to Google Ads, GA4, CRO, SEO, and AI Visibility.",
    machineSummary: "Service entity connected to Shopify, Google Merchant Center, Google Ads, GA4, CRO, speed, structured product data, Dubai retail, and e-commerce case studies.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-technology-shopify", "kg-technology-google-merchant"],
    relatedObjects: ["kg-service-google-ads", "kg-technology-ga4", "kg-service-cro", "kg-industry-retail"],
    schemaId: `${siteConfig.url}/services/shopify-development-dubai#service`,
    keywords: ["Shopify development Dubai", "Shopify agency UAE", "Shopify SEO Dubai"],
    semanticTags: ["shopify", "commerce", "cro", "seo", "performance"],
    confidenceScore: 91,
    authorityScore: 84,
    lastUpdated: updated,
    language: "en-AE",
    href: "/services/shopify-development-dubai",
  },
  {
    uuid: "kg-service-google-ads",
    type: "Service",
    name: "Google Ads",
    slug: "google-ads",
    aliases: ["Google Ads Dubai", "Performance Max", "PMax"],
    description: "Paid search and performance advertising connected to conversion tracking, landing pages, CRO, Shopify, and measurement.",
    summary: "Google Ads connects Performance Max, GA4, server-side tracking, Shopify, CRO, and business growth.",
    machineSummary: "Service entity connected to Performance Max, GA4, Conversion API, server-side tracking, Shopify, CRO, AI Visibility, Dubai, retail, statistics, FAQ, downloads, prompts, and checklists.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-technology-performance-max", "kg-technology-ga4", "kg-technology-conversion-api"],
    relatedObjects: ["kg-service-shopify", "kg-service-cro", "kg-city-dubai", "kg-dataset-google-ads-cpc-uae"],
    schemaId: `${siteConfig.url}/google-ads-dubai#service`,
    keywords: ["Google Ads Dubai", "Performance Max UAE", "Google Ads management Dubai"],
    semanticTags: ["paid-media", "google-ads", "measurement", "cro"],
    confidenceScore: 90,
    authorityScore: 82,
    lastUpdated: updated,
    language: "en-AE",
    href: "/google-ads-dubai",
  },
  {
    uuid: "kg-service-automation",
    type: "Service",
    name: "Business Automation",
    slug: "business-automation",
    aliases: ["AI automation", "workflow automation", "CRM automation"],
    description: "Automation systems for lead routing, content operations, CRM workflows, reporting, and AI-assisted business processes.",
    summary: "Automation connects CRM, AI tools, lead qualification, reporting, and content production.",
    machineSummary: "Service entity connected to AI tools, CRM, automation, lead qualification, workflow design, and digital growth systems.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-tool-prompt-builder", "kg-api-knowledge"],
    relatedObjects: ["kg-service-ai-visibility", "kg-service-google-ads", "kg-service-shopify"],
    schemaId: `${siteConfig.url}/crm#automation`,
    keywords: ["business automation UAE", "AI automation Dubai", "CRM automation"],
    semanticTags: ["automation", "crm", "ai-tools", "workflow"],
    confidenceScore: 86,
    authorityScore: 78,
    lastUpdated: updated,
    language: "en-AE",
    href: "/crm",
  },
  {
    uuid: "kg-service-seo",
    type: "Service",
    name: "SEO Optimization",
    slug: "seo-optimization",
    aliases: ["SEO Dubai", "technical SEO", "search engine optimization"],
    description: "Search optimization for crawlability, metadata, site architecture, content clusters, internal links, and AI-ready discovery.",
    summary: "SEO is connected to AEO, GEO, crawlability, structured data, and topical authority.",
    machineSummary: "Service entity connected to SEO, technical SEO, AEO, GEO, structured data, crawlability, internal linking, content quality, and Dubai businesses.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-glossary-crawlability", "kg-glossary-internal-linking"],
    relatedObjects: ["kg-service-ai-visibility", "kg-service-websites", "kg-glossary-search-intent"],
    schemaId: `${siteConfig.url}/services/seo-optimization#service`,
    keywords: ["SEO services Dubai", "technical SEO Dubai", "SEO agency UAE"],
    semanticTags: ["seo", "technical-seo", "crawlability", "content"],
    confidenceScore: 89,
    authorityScore: 83,
    lastUpdated: updated,
    language: "en-AE",
    href: "/services/seo-optimization",
  },
  {
    uuid: "kg-service-websites",
    type: "Service",
    name: "High-Performance Websites",
    slug: "high-performance-websites",
    aliases: ["web design Dubai", "web development Dubai", "premium websites"],
    description: "Website strategy, design, development, performance, schema, accessibility, and conversion architecture.",
    summary: "Websites serve as the crawlable source of truth for people, search engines, and AI systems.",
    machineSummary: "Service entity connected to web design, development, Core Web Vitals, structured data, AI visibility, conversion, and Dubai service pages.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-stat-core-web-vitals", "kg-process-technical-integrity"],
    relatedObjects: ["kg-service-ai-visibility", "kg-service-seo", "kg-service-shopify"],
    schemaId: `${siteConfig.url}/services/websites#service`,
    keywords: ["web design Dubai", "web development Dubai", "high-performance websites UAE"],
    semanticTags: ["websites", "performance", "schema", "conversion"],
    confidenceScore: 92,
    authorityScore: 85,
    lastUpdated: updated,
    language: "en-AE",
    href: "/services/websites",
  },
  {
    uuid: "kg-service-cro",
    type: "Service",
    name: "Conversion Rate Optimization",
    slug: "conversion-rate-optimization",
    aliases: ["CRO", "conversion engineering", "landing page optimization"],
    description: "Conversion systems that connect landing pages, offer clarity, analytics, performance, UX, and buyer trust.",
    summary: "CRO connects Google Ads, Shopify, websites, performance, and high-ticket conversion architecture.",
    machineSummary: "Service entity connected to CRO, Google Ads, Shopify, landing pages, high-ticket conversion, UX, and business growth.",
    parent: "kg-org-vista-by-lara",
    children: ["kg-tool-cro-calculator"],
    relatedObjects: ["kg-service-google-ads", "kg-service-shopify", "kg-service-websites"],
    schemaId: `${siteConfig.url}/high-ticket-conversion-architecture#cro`,
    keywords: ["conversion rate optimization Dubai", "CRO UAE", "landing page optimization Dubai"],
    semanticTags: ["cro", "conversion", "ux", "analytics"],
    confidenceScore: 86,
    authorityScore: 79,
    lastUpdated: updated,
    language: "en-AE",
    href: "/high-ticket-conversion-architecture",
  },
  {
    uuid: "kg-city-dubai",
    type: "City",
    name: "Dubai",
    slug: "dubai",
    aliases: ["Dubai UAE", "DXB"],
    description: "Primary geographic market for Vista by Lara and the knowledge graph.",
    summary: "Dubai anchors the local SEO, GEO, AEO, service, and research context.",
    machineSummary: "City entity connected to UAE services, AI visibility, Google Ads, Shopify, digital growth, retail, real estate, and professional services.",
    children: [],
    relatedObjects: ["kg-org-vista-by-lara", "kg-service-ai-visibility", "kg-service-google-ads", "kg-service-shopify"],
    schemaId: `${siteConfig.url}/#dubai`,
    keywords: ["Dubai", "UAE", "Dubai digital growth"],
    semanticTags: ["city", "uae", "local-seo", "gcc"],
    confidenceScore: 98,
    authorityScore: 90,
    lastUpdated: updated,
    language: "en-AE",
    href: "/",
  },
  {
    uuid: "kg-industry-retail",
    type: "Industry",
    name: "Retail",
    slug: "retail",
    aliases: ["UAE retail", "Dubai retail", "commerce"],
    description: "Retail industry pages, tools, benchmarks, and case-study relationships for Dubai and UAE brands.",
    summary: "Retail connects Shopify, Google Ads, CRO, AI visibility, and product data quality.",
    machineSummary: "Industry entity connected to Shopify, Google Ads, Performance Max, Merchant Center, CRO, AI visibility, and case studies.",
    children: [],
    relatedObjects: ["kg-service-shopify", "kg-service-google-ads", "kg-technology-google-merchant", "kg-service-cro"],
    schemaId: `${siteConfig.url}/industries/retail#industry`,
    keywords: ["retail marketing Dubai", "retail ecommerce UAE", "retail growth systems"],
    semanticTags: ["retail", "commerce", "shopify", "google-ads"],
    confidenceScore: 88,
    authorityScore: 77,
    lastUpdated: updated,
    language: "en-AE",
    href: "/industries/retail",
  },
  {
    uuid: "kg-technology-performance-max",
    type: "Technology",
    name: "Performance Max",
    slug: "performance-max",
    aliases: ["PMax", "Google Performance Max"],
    description: "Google Ads campaign type connected to conversion data, Merchant Center, audience signals, and creative assets.",
    summary: "Performance Max is a Google Ads technology linked to Shopify, Merchant Center, and conversion tracking.",
    machineSummary: "Technology entity connected to Google Ads, Shopify, Google Merchant Center, GA4, Conversion API, server-side tracking, and CRO.",
    parent: "kg-service-google-ads",
    children: [],
    relatedObjects: ["kg-technology-google-merchant", "kg-technology-ga4", "kg-technology-conversion-api"],
    schemaId: `${siteConfig.url}/entity-map#performance-max`,
    keywords: ["Performance Max UAE", "PMax Dubai", "Google Ads automation"],
    semanticTags: ["google-ads", "performance-max", "measurement"],
    confidenceScore: 84,
    authorityScore: 72,
    lastUpdated: updated,
    language: "en-AE",
    href: "/entity-map",
  },
  {
    uuid: "kg-technology-ga4",
    type: "Technology",
    name: "GA4",
    slug: "ga4",
    aliases: ["Google Analytics 4", "Analytics"],
    description: "Analytics platform used for measurement, event tracking, attribution, and reporting.",
    summary: "GA4 connects Google Ads, CRO, Shopify, reporting, and conversion measurement.",
    machineSummary: "Technology entity connected to Google Ads, CRO, Shopify analytics, Conversion API, server-side tracking, and reporting.",
    parent: "kg-service-google-ads",
    children: [],
    relatedObjects: ["kg-service-google-ads", "kg-service-cro", "kg-service-shopify"],
    schemaId: `${siteConfig.url}/entity-map#ga4`,
    keywords: ["GA4 Dubai", "Google Analytics UAE", "conversion tracking"],
    semanticTags: ["analytics", "measurement", "google"],
    confidenceScore: 84,
    authorityScore: 72,
    lastUpdated: updated,
    language: "en-AE",
    href: "/entity-map",
  },
  {
    uuid: "kg-technology-conversion-api",
    type: "Technology",
    name: "Conversion API",
    slug: "conversion-api",
    aliases: ["CAPI", "server-side conversion tracking"],
    description: "Server-connected conversion data used to improve measurement and attribution reliability.",
    summary: "Conversion API connects ads, analytics, server-side tracking, and CRO.",
    machineSummary: "Technology entity connected to Google Ads, Meta, GA4, server-side tracking, Shopify, and conversion optimization.",
    parent: "kg-service-google-ads",
    children: [],
    relatedObjects: ["kg-technology-ga4", "kg-service-cro", "kg-service-shopify"],
    schemaId: `${siteConfig.url}/entity-map#conversion-api`,
    keywords: ["Conversion API UAE", "server side tracking Dubai", "ad tracking reliability"],
    semanticTags: ["tracking", "analytics", "conversion"],
    confidenceScore: 82,
    authorityScore: 70,
    lastUpdated: updated,
    language: "en-AE",
    href: "/entity-map",
  },
  {
    uuid: "kg-technology-google-merchant",
    type: "Technology",
    name: "Google Merchant Center",
    slug: "google-merchant-center",
    aliases: ["Google Merchant", "Merchant Center"],
    description: "Product feed and commerce platform connected to Shopify, Performance Max, product data, and retail advertising.",
    summary: "Google Merchant Center connects Shopify product data to Google Ads and Performance Max.",
    machineSummary: "Technology entity connected to Shopify, Google Ads, product feeds, Performance Max, retail, and ecommerce growth.",
    parent: "kg-service-shopify",
    children: [],
    relatedObjects: ["kg-service-shopify", "kg-service-google-ads", "kg-technology-performance-max"],
    schemaId: `${siteConfig.url}/entity-map#google-merchant-center`,
    keywords: ["Google Merchant Center UAE", "Shopify product feeds", "Performance Max retail"],
    semanticTags: ["merchant-center", "shopify", "retail", "google-ads"],
    confidenceScore: 82,
    authorityScore: 70,
    lastUpdated: updated,
    language: "en-AE",
    href: "/entity-map",
  },
  {
    uuid: "kg-technology-shopify",
    type: "Software",
    name: "Shopify",
    slug: "shopify",
    aliases: ["Shopify Plus", "Shopify UAE"],
    description: "Commerce software platform connected to product data, performance, SEO, CRO, and paid media.",
    summary: "Shopify is a software entity connected to commerce services and growth systems.",
    machineSummary: "Software entity connected to Shopify development, Google Merchant Center, Google Ads, CRO, product data, and retail.",
    parent: "kg-service-shopify",
    children: [],
    relatedObjects: ["kg-service-shopify", "kg-technology-google-merchant", "kg-service-google-ads"],
    schemaId: `${siteConfig.url}/entity-map#shopify`,
    keywords: ["Shopify", "Shopify UAE", "Shopify development Dubai"],
    semanticTags: ["software", "commerce", "shopify"],
    confidenceScore: 88,
    authorityScore: 76,
    lastUpdated: updated,
    language: "en-AE",
    href: "/services/shopify-development-dubai",
  },
  {
    uuid: "kg-process-recommendation-confidence",
    type: "Process",
    name: "Vista Recommendation Confidence Model",
    slug: "vista-recommendation-confidence-model",
    aliases: ["Recommendation Confidence", "Vista AI visibility model"],
    description: "Vista by Lara methodology for assessing whether AI systems can identify, trust, and describe a business.",
    summary: "The model organizes AI visibility into entity clarity, technical foundation, digital trust, authority, knowledge graph, and recommendation confidence.",
    machineSummary: "Process entity connected to AI Visibility, Knowledge Asset 001, entity clarity, technical foundation, digital trust, authority, knowledge graph, and recommendation confidence.",
    parent: "kg-guide-ai-recommendations",
    children: [],
    relatedObjects: ["kg-service-ai-visibility", "kg-tool-ai-visibility-score", "kg-glossary-knowledge-graph"],
    schemaId: `${siteConfig.url}/knowledge/ai-visibility/why-ai-isnt-recommending-your-business#vista-recommendation-confidence-model`,
    keywords: ["Vista Recommendation Confidence Model", "AI visibility framework", "recommendation confidence"],
    semanticTags: ["methodology", "ai-visibility", "framework"],
    confidenceScore: 94,
    authorityScore: 86,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/ai-visibility/why-ai-isnt-recommending-your-business",
  },
  {
    uuid: "kg-tool-ai-visibility-score",
    type: "Tool",
    name: "AI Visibility Score",
    slug: "ai-visibility-score",
    aliases: ["AI readiness score", "AI recommendation score"],
    description: "Coming-soon tool for evaluating structured data, business profile clarity, trust, content depth, links, mentions, performance, and authority.",
    summary: "The AI Visibility Score will become the first interactive scoring tool in the Vista AI lab.",
    machineSummary: "Tool entity connected to AI Visibility, structured data, reviews, content depth, internal linking, mentions, entity consistency, performance, and authority.",
    parent: "kg-service-ai-visibility",
    children: [],
    relatedObjects: ["kg-service-ai-visibility", "kg-process-recommendation-confidence", "kg-guide-ai-recommendations"],
    schemaId: `${siteConfig.url}/tools/ai-visibility-score#tool`,
    keywords: ["AI visibility score", "AI readiness score", "GEO audit tool"],
    semanticTags: ["tool", "score", "ai-readiness", "audit"],
    confidenceScore: 78,
    authorityScore: 66,
    lastUpdated: updated,
    language: "en-AE",
    href: "/tools/ai-visibility-score",
  },
  {
    uuid: "kg-api-knowledge",
    type: "API",
    name: "Vista Knowledge API",
    slug: "vista-knowledge-api",
    aliases: ["Knowledge API", "AI-readable API"],
    description: "Machine-readable JSON endpoints for services, entities, FAQ, research, statistics, tools, authors, glossary, videos, checklists, and templates.",
    summary: "The Knowledge API exposes Vista by Lara content objects for crawlers, integrations, and AI systems.",
    machineSummary: "API entity connected to machine-readable discovery, services, entities, FAQ, research, statistics, tools, authors, glossary, videos, checklists, templates, and AI agent index.",
    children: [],
    relatedObjects: ["kg-org-vista-by-lara", "kg-service-ai-visibility", "kg-tool-ai-visibility-score"],
    schemaId: `${siteConfig.url}/api#api`,
    keywords: ["knowledge API", "AI-readable API", "machine-readable website"],
    semanticTags: ["api", "json", "ai-readable", "knowledge-graph"],
    confidenceScore: 85,
    authorityScore: 80,
    lastUpdated: updated,
    language: "en-AE",
    href: "/api",
  },
  {
    uuid: "kg-award-noble-business",
    type: "Award",
    name: "Noble Business Winner 2025 - Business Innovation",
    slug: "noble-business-winner-2025",
    aliases: ["Noble Business Award", "Business Innovation Winner"],
    description: "Award signal referenced by Vista by Lara as part of the trust dashboard and organizational authority profile.",
    summary: "Award object connected to Vista by Lara trust and EEAT signals.",
    machineSummary: "Award entity connected to organization, trust dashboard, EEAT, authority, and credibility signals.",
    parent: "kg-org-vista-by-lara",
    children: [],
    relatedObjects: ["kg-org-vista-by-lara"],
    schemaId: `${siteConfig.url}/trust#noble-business-winner-2025`,
    keywords: ["Noble Business Winner 2025", "Business Innovation", "Vista by Lara award"],
    semanticTags: ["award", "trust", "eeat"],
    confidenceScore: 88,
    authorityScore: 82,
    lastUpdated: updated,
    language: "en-AE",
    href: "/trust",
  },
  {
    uuid: "kg-research-ai-visibility-index",
    type: "Research",
    name: "Vista AI Visibility Index",
    slug: "vista-ai-visibility-index",
    aliases: ["AI Visibility Index", "UAE AI visibility report"],
    description: "Planned original research tracking AI discoverability, entity clarity, citation frequency, and recommendation signals in UAE markets.",
    summary: "Research object for the AI Visibility Index roadmap.",
    machineSummary: "Research entity connected to AI Visibility, AI recommendation studies, citation frequency, datasets, methodology, and UAE benchmarks.",
    children: ["kg-dataset-ai-recommendation-index"],
    relatedObjects: ["kg-service-ai-visibility", "kg-guide-ai-recommendations", "kg-tool-ai-visibility-score"],
    schemaId: `${siteConfig.url}/research#vista-ai-visibility-index`,
    keywords: ["AI Visibility Index UAE", "AI recommendation study", "AI citation frequency"],
    semanticTags: ["research", "dataset", "benchmark", "ai-visibility"],
    confidenceScore: 72,
    authorityScore: 68,
    lastUpdated: updated,
    language: "en-AE",
    href: "/research",
  },
  {
    uuid: "kg-dataset-google-ads-cpc-uae",
    type: "Dataset",
    name: "Google Ads CPC UAE Dataset",
    slug: "google-ads-cpc-uae",
    aliases: ["UAE Google Ads CPC", "Google Ads benchmarks UAE"],
    description: "Planned dataset for UAE Google Ads CPC benchmarks, methodology, CSV, JSON, and citation records.",
    summary: "Dataset object for future Google Ads UAE benchmark research.",
    machineSummary: "Dataset entity connected to Google Ads, CPC, UAE benchmarks, charts, methodology, CSV, JSON, and research center.",
    parent: "kg-service-google-ads",
    children: [],
    relatedObjects: ["kg-service-google-ads", "kg-research-google-ads-benchmarks"],
    schemaId: `${siteConfig.url}/research#google-ads-cpc-uae`,
    keywords: ["Google Ads CPC UAE", "Google Ads benchmarks Dubai", "paid media dataset"],
    semanticTags: ["dataset", "google-ads", "cpc", "uae"],
    confidenceScore: 68,
    authorityScore: 64,
    lastUpdated: updated,
    language: "en-AE",
    href: "/research",
  },
  {
    uuid: "kg-dataset-ai-recommendation-index",
    type: "Dataset",
    name: "AI Recommendation Index",
    slug: "ai-recommendation-index",
    aliases: ["AI recommendation dataset", "AI citation dataset"],
    description: "Planned dataset for tracking how often AI systems cite, mention, and recommend businesses across UAE categories.",
    summary: "Dataset object for AI recommendation and citation frequency research.",
    machineSummary: "Dataset entity connected to AI Visibility, citation frequency, AI recommendation studies, entity clarity, trust signals, and research center.",
    parent: "kg-research-ai-visibility-index",
    children: [],
    relatedObjects: ["kg-service-ai-visibility", "kg-research-ai-visibility-index"],
    schemaId: `${siteConfig.url}/research#ai-recommendation-index`,
    keywords: ["AI recommendation index", "AI citation frequency UAE", "AI visibility dataset"],
    semanticTags: ["dataset", "ai-visibility", "citation", "recommendation"],
    confidenceScore: 70,
    authorityScore: 66,
    lastUpdated: updated,
    language: "en-AE",
    href: "/research",
  },
  {
    uuid: "kg-research-google-ads-benchmarks",
    type: "Research",
    name: "UAE Google Ads Benchmarks",
    slug: "uae-google-ads-benchmarks",
    aliases: ["Google Ads benchmarks UAE", "paid media benchmarks Dubai"],
    description: "Planned research report covering UAE Google Ads benchmark methodology, datasets, charts, and citation format.",
    summary: "Research object for future paid media benchmark publication.",
    machineSummary: "Research entity connected to Google Ads, Performance Max, CPC dataset, conversion rates, methodology, charts, and downloadable CSV/JSON.",
    children: ["kg-dataset-google-ads-cpc-uae"],
    relatedObjects: ["kg-service-google-ads", "kg-technology-performance-max", "kg-technology-ga4"],
    schemaId: `${siteConfig.url}/research#uae-google-ads-benchmarks`,
    keywords: ["UAE Google Ads benchmarks", "Dubai paid media report", "Performance Max benchmarks"],
    semanticTags: ["research", "google-ads", "benchmark", "uae"],
    confidenceScore: 70,
    authorityScore: 66,
    lastUpdated: updated,
    language: "en-AE",
    href: "/research",
  },
  {
    uuid: "kg-stat-core-web-vitals",
    type: "Statistic",
    name: "Core Web Vitals Performance Signal",
    slug: "core-web-vitals-performance-signal",
    aliases: ["CWV", "website performance"],
    description: "Internal quality signal used in Vista resources to connect technical performance with crawl efficiency and conversion trust.",
    summary: "Statistic object placeholder for future UAE website performance benchmarks.",
    machineSummary: "Statistic entity connected to high-performance websites, SEO, crawlability, UX, Core Web Vitals, and future datasets.",
    parent: "kg-service-websites",
    children: [],
    relatedObjects: ["kg-service-websites", "kg-service-seo", "kg-service-ai-visibility"],
    schemaId: `${siteConfig.url}/research#core-web-vitals`,
    keywords: ["Core Web Vitals UAE", "website performance Dubai", "crawl efficiency"],
    semanticTags: ["statistic", "performance", "websites"],
    confidenceScore: 76,
    authorityScore: 68,
    lastUpdated: updated,
    language: "en-AE",
    href: "/research",
  },
  {
    uuid: "kg-faq-ai-visibility",
    type: "FAQ",
    name: "What does AI visibility mean?",
    slug: "what-does-ai-visibility-mean",
    aliases: ["AI visibility FAQ", "AI search FAQ"],
    description: "FAQ object defining AI visibility in direct answer format.",
    summary: "AI visibility is the ability of AI systems to identify, trust, and mention a business.",
    machineSummary: "FAQ entity connected to AI Visibility Hub, Knowledge Asset 001, GEO, AEO, and digital trust.",
    parent: "kg-service-ai-visibility",
    children: [],
    relatedObjects: ["kg-service-ai-visibility", "kg-guide-ai-recommendations"],
    schemaId: `${siteConfig.url}/knowledge/ai-visibility#faq-ai-visibility`,
    keywords: ["what is AI visibility", "AI visibility definition", "AEO FAQ"],
    semanticTags: ["faq", "definition", "ai-visibility"],
    confidenceScore: 92,
    authorityScore: 84,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/ai-visibility",
  },
  {
    uuid: "kg-glossary-geo",
    type: "Glossary",
    name: "Generative Engine Optimization",
    slug: "generative-engine-optimization",
    aliases: ["GEO", "Generative AI optimization"],
    description: "The practice of making content easier for generative AI systems to retrieve, interpret, summarize, and cite.",
    summary: "GEO is a core AI visibility concept.",
    machineSummary: "Glossary entity connected to AI Visibility, AEO, structured data, retrieval, semantic search, and AI answers.",
    parent: "kg-service-ai-visibility",
    children: [],
    relatedObjects: ["kg-glossary-aeo", "kg-glossary-knowledge-graph", "kg-guide-ai-recommendations"],
    schemaId: `${siteConfig.url}/knowledge/glossary#generative-engine-optimization-geo`,
    keywords: ["GEO", "Generative Engine Optimization", "AI search optimization"],
    semanticTags: ["glossary", "geo", "ai-search"],
    confidenceScore: 92,
    authorityScore: 84,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/glossary#generative-engine-optimization-geo",
  },
  {
    uuid: "kg-glossary-aeo",
    type: "Glossary",
    name: "Answer Engine Optimization",
    slug: "answer-engine-optimization",
    aliases: ["AEO", "answer optimization"],
    description: "The practice of formatting content so answer engines can extract concise, direct responses.",
    summary: "AEO supports direct answers, FAQs, and answer-ready headings.",
    machineSummary: "Glossary entity connected to AI Visibility, FAQ, direct answers, structured content, search intent, and answer engines.",
    parent: "kg-service-ai-visibility",
    children: [],
    relatedObjects: ["kg-glossary-geo", "kg-faq-ai-visibility"],
    schemaId: `${siteConfig.url}/knowledge/glossary#answer-engine-optimization-aeo`,
    keywords: ["AEO", "Answer Engine Optimization", "FAQ optimization"],
    semanticTags: ["glossary", "aeo", "answers"],
    confidenceScore: 92,
    authorityScore: 84,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/glossary#answer-engine-optimization-aeo",
  },
  {
    uuid: "kg-glossary-knowledge-graph",
    type: "Glossary",
    name: "Knowledge Graph",
    slug: "knowledge-graph",
    aliases: ["entity graph", "semantic graph"],
    description: "A structured map of entities and relationships that helps systems understand how people, places, services, and topics connect.",
    summary: "Knowledge graphs connect entities so pages are not isolated.",
    machineSummary: "Glossary entity connected to entity map, semantic relationship engine, AI Visibility, structured data, and internal linking.",
    parent: "kg-service-ai-visibility",
    children: [],
    relatedObjects: ["kg-service-ai-visibility", "kg-guide-ai-recommendations", "kg-api-knowledge"],
    schemaId: `${siteConfig.url}/knowledge/glossary#knowledge-graph`,
    keywords: ["knowledge graph", "entity graph", "semantic relationships"],
    semanticTags: ["glossary", "knowledge-graph", "entities"],
    confidenceScore: 92,
    authorityScore: 84,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/glossary#knowledge-graph",
  },
  {
    uuid: "kg-glossary-crawlability",
    type: "Glossary",
    name: "Crawlability",
    slug: "crawlability",
    aliases: ["crawl access", "crawler readability"],
    description: "The ability of search engines and other crawlers to access, read, and follow content on a website.",
    summary: "Crawlability supports SEO, AI retrieval, and knowledge graph completeness.",
    machineSummary: "Glossary entity connected to SEO, technical foundation, AI visibility, internal links, sitemap, and performance.",
    parent: "kg-service-seo",
    children: [],
    relatedObjects: ["kg-service-seo", "kg-service-websites", "kg-service-ai-visibility"],
    schemaId: `${siteConfig.url}/knowledge/glossary#crawlability`,
    keywords: ["crawlability", "technical SEO", "crawler access"],
    semanticTags: ["glossary", "technical-seo", "crawlability"],
    confidenceScore: 90,
    authorityScore: 82,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/glossary#crawlability",
  },
  {
    uuid: "kg-glossary-internal-linking",
    type: "Glossary",
    name: "Internal Linking",
    slug: "internal-linking",
    aliases: ["site links", "semantic internal links"],
    description: "Links between pages on the same website that help users and crawlers understand relationships.",
    summary: "Internal linking connects pages into semantic ecosystems.",
    machineSummary: "Glossary entity connected to SEO, knowledge graph, entity map, crawl efficiency, and topical authority.",
    parent: "kg-service-seo",
    children: [],
    relatedObjects: ["kg-service-seo", "kg-service-ai-visibility", "kg-glossary-knowledge-graph"],
    schemaId: `${siteConfig.url}/knowledge/glossary#internal-linking`,
    keywords: ["internal linking", "semantic links", "crawl efficiency"],
    semanticTags: ["glossary", "links", "crawl-efficiency"],
    confidenceScore: 90,
    authorityScore: 82,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/glossary#internal-linking",
  },
  {
    uuid: "kg-glossary-search-intent",
    type: "Glossary",
    name: "Search Intent",
    slug: "search-intent",
    aliases: ["query intent", "buyer intent"],
    description: "The underlying goal behind a query, such as learning, comparing, buying, or finding a specific brand.",
    summary: "Search intent connects content strategy to buyer problems.",
    machineSummary: "Glossary entity connected to SEO, AEO, AI visibility, content quality, FAQs, and conversion.",
    parent: "kg-service-seo",
    children: [],
    relatedObjects: ["kg-service-seo", "kg-service-ai-visibility", "kg-service-cro"],
    schemaId: `${siteConfig.url}/knowledge/glossary#search-intent`,
    keywords: ["search intent", "buyer intent", "SEO content strategy"],
    semanticTags: ["glossary", "intent", "seo"],
    confidenceScore: 90,
    authorityScore: 82,
    lastUpdated: updated,
    language: "en-AE",
    href: "/knowledge/glossary#search-intent",
  },
  {
    uuid: "kg-tool-prompt-builder",
    type: "Tool",
    name: "Prompt Builder",
    slug: "prompt-builder",
    aliases: ["AI prompt tool", "prompt library"],
    description: "Planned interactive tool for creating reusable prompts for audits, FAQs, briefs, and AI-ready content operations.",
    summary: "Prompt Builder is part of the future Vista AI lab.",
    machineSummary: "Tool entity connected to prompt library, AI content enrichment, automation, templates, and knowledge production workflows.",
    children: [],
    relatedObjects: ["kg-service-automation", "kg-api-knowledge", "kg-template-content-brief"],
    schemaId: `${siteConfig.url}/tools#prompt-builder`,
    keywords: ["prompt builder", "AI prompt library", "content prompts"],
    semanticTags: ["tool", "prompt", "automation"],
    confidenceScore: 70,
    authorityScore: 62,
    lastUpdated: updated,
    language: "en-AE",
    href: "/tools",
  },
  {
    uuid: "kg-tool-cro-calculator",
    type: "Tool",
    name: "CRO Calculator",
    slug: "cro-calculator",
    aliases: ["conversion calculator", "CRO score"],
    description: "Planned calculator for estimating conversion opportunities from traffic, conversion rate, lead quality, and value.",
    summary: "CRO Calculator is part of the future Vista interactive lab.",
    machineSummary: "Tool entity connected to CRO, Google Ads, Shopify, conversion rates, landing pages, and business growth.",
    children: [],
    relatedObjects: ["kg-service-cro", "kg-service-google-ads", "kg-service-shopify"],
    schemaId: `${siteConfig.url}/tools#cro-calculator`,
    keywords: ["CRO calculator", "conversion calculator Dubai", "landing page calculator"],
    semanticTags: ["tool", "cro", "conversion"],
    confidenceScore: 70,
    authorityScore: 62,
    lastUpdated: updated,
    language: "en-AE",
    href: "/tools",
  },
  {
    uuid: "kg-template-content-brief",
    type: "Template",
    name: "AI-Readable Content Brief",
    slug: "ai-readable-content-brief",
    aliases: ["content brief template", "GEO brief"],
    description: "Planned template for producing article packages with metadata, entities, FAQs, schema, internal links, and AI summaries.",
    summary: "Template object for the Vista content production workflow.",
    machineSummary: "Template entity connected to content enrichment, entity strategy, FAQ, schema, metadata, internal linking, and publishing workflow.",
    children: [],
    relatedObjects: ["kg-service-ai-visibility", "kg-api-knowledge", "kg-tool-prompt-builder"],
    schemaId: `${siteConfig.url}/api/templates#ai-readable-content-brief`,
    keywords: ["content brief template", "GEO content brief", "AI-readable content"],
    semanticTags: ["template", "content", "geo", "workflow"],
    confidenceScore: 76,
    authorityScore: 68,
    lastUpdated: updated,
    language: "en-AE",
    href: "/api/templates",
  },
  {
    uuid: "kg-process-technical-integrity",
    type: "Process",
    name: "Technical Integrity Audit",
    slug: "technical-integrity-audit",
    aliases: ["infrastructure audit", "technical audit"],
    description: "Vista process for reviewing technical quality, crawlability, performance, schema, API latency, and digital trust infrastructure.",
    summary: "Technical Integrity Audit is a trust and performance process.",
    machineSummary: "Process entity connected to websites, SEO, AI visibility, schema, crawlability, performance, and infrastructure briefing.",
    children: [],
    relatedObjects: ["kg-service-websites", "kg-service-seo", "kg-service-ai-visibility"],
    schemaId: `${siteConfig.url}/contact#technical-integrity-audit`,
    keywords: ["technical audit Dubai", "technical integrity audit", "infrastructure audit"],
    semanticTags: ["process", "audit", "performance", "trust"],
    confidenceScore: 84,
    authorityScore: 76,
    lastUpdated: updated,
    language: "en-AE",
    href: "/contact",
  },
]

export const semanticRelationships: SemanticRelationship[] = [
  { source: "kg-service-google-ads", target: "kg-technology-performance-max", relationship: "uses", strength: 9 },
  { source: "kg-technology-performance-max", target: "kg-technology-conversion-api", relationship: "depends on conversion signals from", strength: 8 },
  { source: "kg-technology-conversion-api", target: "kg-technology-ga4", relationship: "connects measurement with", strength: 8 },
  { source: "kg-technology-ga4", target: "kg-service-shopify", relationship: "measures commerce behavior for", strength: 8 },
  { source: "kg-service-shopify", target: "kg-service-cro", relationship: "benefits from", strength: 8 },
  { source: "kg-service-cro", target: "kg-service-ai-visibility", relationship: "supports trust and clarity for", strength: 7 },
  { source: "kg-service-ai-visibility", target: "kg-city-dubai", relationship: "targets discovery in", strength: 9 },
  { source: "kg-city-dubai", target: "kg-industry-retail", relationship: "contains market demand for", strength: 7 },
  { source: "kg-industry-retail", target: "kg-guide-ai-recommendations", relationship: "uses guidance from", strength: 6 },
  { source: "kg-guide-ai-recommendations", target: "kg-faq-ai-visibility", relationship: "answers", strength: 8 },
  { source: "kg-faq-ai-visibility", target: "kg-tool-ai-visibility-score", relationship: "leads to", strength: 7 },
  { source: "kg-tool-ai-visibility-score", target: "kg-template-content-brief", relationship: "can generate", strength: 6 },
  { source: "kg-template-content-brief", target: "kg-process-recommendation-confidence", relationship: "supports", strength: 8 },
  { source: "kg-service-ai-visibility", target: "kg-glossary-geo", relationship: "includes", strength: 9 },
  { source: "kg-service-ai-visibility", target: "kg-glossary-aeo", relationship: "includes", strength: 9 },
  { source: "kg-service-ai-visibility", target: "kg-glossary-knowledge-graph", relationship: "depends on", strength: 8 },
  { source: "kg-service-seo", target: "kg-glossary-crawlability", relationship: "requires", strength: 9 },
  { source: "kg-service-seo", target: "kg-glossary-internal-linking", relationship: "uses", strength: 9 },
  { source: "kg-research-ai-visibility-index", target: "kg-dataset-ai-recommendation-index", relationship: "publishes", strength: 9 },
  { source: "kg-research-google-ads-benchmarks", target: "kg-dataset-google-ads-cpc-uae", relationship: "publishes", strength: 9 },
]

export const researchReports = knowledgeObjects.filter((item) => item.type === "Research")
export const datasets = knowledgeObjects.filter((item) => item.type === "Dataset")
export const tools = knowledgeObjects.filter((item) => item.type === "Tool")
export const glossaryTerms = knowledgeObjects.filter((item) => item.type === "Glossary")
export const services = knowledgeObjects.filter((item) => item.type === "Service")
export const faqs = knowledgeObjects.filter((item) => item.type === "FAQ")
export const templates = knowledgeObjects.filter((item) => item.type === "Template")
export const statistics = knowledgeObjects.filter((item) => item.type === "Statistic")

export const competitors = [
  {
    id: "competitor-nexa",
    name: "Nexa",
    url: "https://www.digitalnexa.com/",
    market: "Dubai, UAE, GCC, international",
    category: "Digital growth agency",
    observedPositioning: "End-to-end AI and digital solutions, digital marketing, website development, SEO, lead generation, HubSpot CRM, social media, video production, and AI Lab services.",
    observedStrengths: [
      "Long-established agency signal",
      "Large team and multi-office footprint",
      "HubSpot and CRM authority",
      "Broad case-study and client-logo surface",
      "AI Lab and Generative Search Optimisation service labels",
    ],
    vistaCounterPosition: "Vista by Lara should compete with a narrower principal-led AI visibility and machine-readable authority position: public AI data, entity graph, structured knowledge assets, technical SEO, AEO, GEO, and high-performance website infrastructure for UAE principals.",
    comparisonQueries: ["Nexa alternative Dubai", "Nexa vs Vista by Lara", "AI visibility agency Dubai", "digital marketing agency Dubai"],
  },
  {
    id: "competitor-digital-gravity",
    name: "Digital Gravity",
    url: "https://www.digitalgravity.ae/",
    market: "Dubai, UAE, Saudi Arabia, USA, Pakistan",
    category: "Web design and digital agency",
    observedPositioning: "Web design, website development, mobile app development, SEO, SMM, PPC, branding, and digital production with broad digital-breakthrough messaging.",
    observedStrengths: [
      "Strong web design and development category signal",
      "Broad service coverage across website, app, SEO, SMM, PPC, print, and branding",
      "Regional and global presence cues",
      "Portfolio-led proof structure",
    ],
    vistaCounterPosition: "Vista by Lara should avoid generic web-agency framing and emphasize AI-search authority engineering, structured data, public AI-readable endpoints, UAE entity mapping, and conversion architecture.",
    comparisonQueries: ["Digital Gravity alternative Dubai", "Digital Gravity vs Vista by Lara", "web design Dubai AI visibility", "website development UAE"],
  },
  {
    id: "competitor-global-media-insight",
    name: "Global Media Insight",
    url: "https://www.globalmediainsight.com/",
    market: "Dubai, UAE",
    category: "SEO and digital marketing agency",
    observedPositioning: "SEO, GEO services Dubai, ChatGPT SEO, Perplexity SEO, AI SEO, Claude SEO, AI Overview Optimization, local SEO, Arabic SEO, multilingual SEO, analytics, and industry SEO.",
    observedStrengths: [
      "Very broad SEO taxonomy",
      "Explicit AI-search service labels",
      "Arabic and multilingual SEO coverage",
      "Industry-specific SEO pages",
    ],
    vistaCounterPosition: "Vista by Lara should counter with stronger evidence architecture: entity graph, knowledge platform, case-study registry, schema governance, and principal-to-principal technical audits rather than only service taxonomy breadth.",
    comparisonQueries: ["Global Media Insight alternative Dubai", "ChatGPT SEO Dubai agency", "GEO services Dubai", "AI SEO UAE"],
  },
  {
    id: "competitor-united-seo",
    name: "United SEO",
    url: "https://www.unitedseo.ae/",
    market: "Dubai, UAE",
    category: "SEO agency",
    observedPositioning: "SEO Dubai, SEO agency, Google organic ranking, website optimization, content creation, backlinks, digital consultancy, and case-study-led SEO proof.",
    observedStrengths: [
      "Focused SEO Dubai keyword alignment",
      "Case-study surface across Dubai industries",
      "Clear organic ranking and SEO consultancy positioning",
    ],
    vistaCounterPosition: "Vista by Lara should win higher-intent AI-era queries by connecting SEO to AEO, GEO, structured data, answer extraction, machine-readable authority, and AI recommendation confidence.",
    comparisonQueries: ["United SEO alternative Dubai", "SEO agency Dubai AI visibility", "technical SEO audit Dubai", "AEO agency Dubai"],
  },
  {
    id: "competitor-seo-sherpa",
    name: "SEO Sherpa",
    url: "https://seosherpa.com/",
    market: "Dubai, UAE, international",
    category: "SEO agency",
    observedPositioning: "SEO agency associated with organic search, technical SEO, content, link building, and performance-led SEO campaigns for competitive markets.",
    observedStrengths: [
      "Strong SEO-specialist positioning",
      "Recognizable Dubai SEO category signal",
      "Performance and organic growth language",
      "Authority-building service coverage",
    ],
    vistaCounterPosition: "Vista by Lara should differentiate through AI-era SEO, AEO, GEO, entity graph clarity, public AI-readable data, structured knowledge assets, and technical infrastructure audits for UAE principals.",
    comparisonQueries: ["SEO Sherpa alternative Dubai", "SEO Sherpa vs Vista by Lara", "AI SEO Dubai", "GEO services Dubai"],
  },
  {
    id: "competitor-traffic-digital",
    name: "Traffic Digital",
    url: "https://www.wearetraffic.com/",
    market: "Dubai, UAE, GCC",
    category: "Digital marketing agency",
    observedPositioning: "Regional digital agency associated with strategy, creative, technology, media, SEO, analytics, and broad digital transformation services.",
    observedStrengths: [
      "Regional agency footprint",
      "Broad digital service range",
      "Enterprise and transformation cues",
      "Integrated strategy and media language",
    ],
    vistaCounterPosition: "Vista by Lara should compete where principals need a focused AI visibility and technical authority studio rather than broad digital transformation delivery.",
    comparisonQueries: ["Traffic Digital alternative Dubai", "digital marketing company Dubai comparison", "AI visibility agency Dubai", "technical SEO Dubai"],
  },
  {
    id: "competitor-chain-reaction",
    name: "Chain Reaction",
    url: "https://www.chainreaction.ae/",
    market: "Dubai, UAE, Saudi Arabia, Jordan",
    category: "Digital marketing and performance agency",
    observedPositioning: "Performance and digital marketing agency associated with SEO, paid media, social, creative, analytics, and regional campaign delivery.",
    observedStrengths: [
      "Performance marketing category signal",
      "Regional MENA market presence",
      "SEO and paid media service breadth",
      "Campaign and analytics positioning",
    ],
    vistaCounterPosition: "Vista by Lara should differentiate through AI-search authority engineering, structured retrieval assets, entity confidence, and technical conversion architecture for premium UAE brands.",
    comparisonQueries: ["Chain Reaction alternative Dubai", "performance marketing Dubai AI SEO", "AEO agency Dubai", "Google AI Overview optimization Dubai"],
  },
  {
    id: "competitor-prism-digital",
    name: "Prism Digital",
    url: "https://www.prism-me.com/",
    market: "Dubai, UAE",
    category: "Digital marketing agency",
    observedPositioning: "Dubai digital agency associated with SEO, social media, paid advertising, web design, video, branding, and digital growth campaigns.",
    observedStrengths: [
      "Broad Dubai digital marketing coverage",
      "SEO, paid ads, and social service pages",
      "Creative and video production cues",
      "Local Dubai agency relevance",
    ],
    vistaCounterPosition: "Vista by Lara should win higher-intent technical searches by connecting SEO, AEO, GEO, AI-readable data, knowledge assets, and principal-led implementation.",
    comparisonQueries: ["Prism Digital alternative Dubai", "digital marketing agency Dubai alternative", "AEO agency Dubai", "AI search optimization UAE"],
  },
  {
    id: "competitor-red-berries",
    name: "Red Berries",
    url: "https://redberries.ae/",
    market: "Dubai, UAE",
    category: "Digital marketing agency",
    observedPositioning: "Dubai agency associated with web design, SEO, social media, branding, paid campaigns, content, and digital marketing execution.",
    observedStrengths: [
      "Local Dubai digital agency signal",
      "Website and SEO service coverage",
      "Social and paid campaign offerings",
      "SME-friendly service breadth",
    ],
    vistaCounterPosition: "Vista by Lara should differentiate through premium technical infrastructure, AI visibility, schema governance, entity strategy, and conversion paths for principals.",
    comparisonQueries: ["Red Berries alternative Dubai", "web design Dubai AI visibility", "SEO agency Dubai comparison", "GEO agency UAE"],
  },
]

export const apiCatalog = [
  { name: "Services", href: "/ai-data/services", legacyHref: "/api/services", description: "Service entities and semantic relationships." },
  { name: "Entities", href: "/ai-data/entities", legacyHref: "/api/entities", description: "All knowledge graph objects." },
  { name: "FAQ", href: "/ai-data/faq", legacyHref: "/api/faq", description: "FAQ entities and direct-answer records." },
  { name: "Research", href: "/ai-data/research", legacyHref: "/api/research", description: "Research reports, planned datasets, and methodologies." },
  { name: "Statistics", href: "/ai-data/statistics", legacyHref: "/api/statistics", description: "Statistic objects and benchmark placeholders." },
  { name: "Tools", href: "/ai-data/tools", legacyHref: "/api/tools", description: "Interactive tool catalog." },
  { name: "Authors", href: "/ai-data/authors", legacyHref: "/api/authors", description: "Author and reviewer authority records." },
  { name: "Glossary", href: "/ai-data/glossary", legacyHref: "/api/glossary", description: "Glossary definitions." },
  { name: "Videos", href: "/ai-data/videos", legacyHref: "/api/videos", description: "Video catalog placeholder." },
  { name: "Checklists", href: "/ai-data/checklists", legacyHref: "/api/checklists", description: "Checklist and audit workflow objects." },
  { name: "Templates", href: "/ai-data/templates", legacyHref: "/api/templates", description: "Template and prompt-library records." },
  { name: "Competitors", href: "/ai-data/competitors", legacyHref: "/api/competitors", description: "Dubai and UAE digital marketing competitor entities and Vista differentiation map." },
]

export function getKnowledgeApiPayload(resource?: string) {
  const base = {
    name: "Vista Knowledge API",
    version: "1.0",
    lastUpdated: updated,
    language: "en-AE",
    license: "Public discovery endpoint for Vista by Lara knowledge infrastructure.",
    endpoints: apiCatalog,
  }

  switch (resource) {
    case "services":
      return {
        ...base,
        resource,
        items: [
          ...services,
          ...competitorGapServices.map((service) => ({
            uuid: `kg-service-${service.slug}`,
            type: "Service",
            name: service.serviceName,
            slug: service.slug,
            aliases: service.keywords,
            description: service.intro,
            summary: service.subtitle,
            machineSummary: `${service.serviceName} is a Dubai and UAE service entity connected to competitor-gap demand, AI visibility, SEO, AEO, GEO, structured data, and Vista by Lara's public knowledge graph.`,
            parent: "kg-org-vista-by-lara",
            children: [],
            relatedObjects: ["kg-service-ai-visibility", "kg-service-seo", "kg-city-dubai"],
            schemaId: `${siteConfig.url}/services/${service.slug}#service`,
            keywords: service.keywords,
            semanticTags: ["competitor-gap", "dubai", "uae", "ai-search", "service-page"],
            confidenceScore: 88,
            authorityScore: 80,
            lastUpdated: updated,
            language: "en-AE",
            href: `/services/${service.slug}`,
          })),
        ],
        relationships: semanticRelationships,
      }
    case "entities":
      return { ...base, resource, items: knowledgeObjects, relationships: semanticRelationships }
    case "faq":
      return { ...base, resource, items: faqs }
    case "research":
      return { ...base, resource, items: researchReports, datasets }
    case "statistics":
      return { ...base, resource, items: statistics }
    case "tools":
      return { ...base, resource, items: tools }
    case "authors":
      return {
        ...base,
        resource,
        items: [
          {
            id: "author-lara-eros-farbactian",
            name: siteConfig.principal.name,
            title: siteConfig.principal.title,
            credentials:
              "Founder & Principal Architect, Vista by Lara; Noble Business Award Winner 2025 (Business Innovation)",
            sameAs: siteConfig.principal.sameAs,
            reviewedPages: ["/knowledge/ai-visibility/why-ai-isnt-recommending-your-business"],
          },
        ],
      }
    case "glossary":
      return { ...base, resource, items: glossaryTerms }
    case "videos":
      return { ...base, resource, items: [], roadmap: ["AI Visibility explainer", "GEO methodology briefing", "Shopify growth teardown"] }
    case "checklists":
      return {
        ...base,
        resource,
        items: [
          {
            id: "checklist-ai-visibility-readiness",
            name: "AI Visibility Readiness Checklist",
            href: "/tools/ai-visibility-score",
            fields: ["Structured data", "Business profile", "Reviews", "Content depth", "Internal linking", "Mentions", "Entity consistency", "Performance", "Authority"],
          },
        ],
      }
    case "templates":
      return { ...base, resource, items: templates }
    case "competitors":
      return {
        ...base,
        resource,
        market: "Dubai and UAE digital marketing, SEO, AEO, GEO, AI visibility, web design, and growth agency landscape",
        items: competitors,
      }
    default:
      return { ...base, resource: "index", items: knowledgeObjects.slice(0, 8), relationships: semanticRelationships.slice(0, 8) }
  }
}
