/**
 * Central site configuration.
 * Single source of truth for SEO, GEO (generative engine optimization),
 * and AEO (answer engine optimization) metadata across the app.
 */

export const siteConfig = {
  name: "Vista by Lara",
  legalName: "Vista by Lara",
  founder: "Lara Eros Farbactian",
  principal: {
    name: "Lara Eros Farbactian",
    title: "Founder & Principal Architect at Vista by Lara",
    image: "/placeholder-user.jpg",
    bio: "Lara Farbactian, Founder & Principal Architect at Vista by Lara — leading AI-driven digital growth strategy for UAE and GCC brands. Noble Business Award Winner 2025 (Business Innovation).",
    linkedin: "https://www.linkedin.com/in/lara-eros-farbactian-b438782a9/",
    sameAs: [
      "https://www.linkedin.com/in/lara-eros-farbactian-b438782a9/",
      "https://www.linkedin.com/company/vistabylara",
      "https://www.vistabylara.com/about",
    ],
  },
  url: "https://www.vistabylara.com",
  shortDescription: "AI visibility and digital growth agency for UAE & GCC businesses",
  description:
    "Vista by Lara is a Dubai-based AI visibility and digital growth agency helping UAE and GCC businesses get found in Google and recommended by AI answer engines through SEO, AEO/GEO, Shopify optimization, and conversion-focused design.",
  tagline: "AI Visibility, High-Performance Websites & Growth Systems - UAE & GCC",
  email: "solution@vistabylara.com",
  phone: "+971 50 799 4292",
  whatsapp: "https://vista-wa-nurture.vistabylara.workers.dev/wa/general",
  locale: "en_AE",
  foundingYear: 2020,
  teamSize: "10-49",
  pricing: "AED 350-550/hour, projects from AED 18,000",
  address: {
    locality: "Dubai",
    region: "Dubai",
    streetAddress: "Emirates Towers",
    country: "United Arab Emirates",
    countryCode: "AE",
  },
  areaServed: ["UAE", "Dubai", "Abu Dhabi", "Saudi Arabia", "Qatar", "Kuwait"],
  sameAs: [
    "https://www.instagram.com/vistabylara",
    "https://www.tiktok.com/@vistabylara",
    "https://www.linkedin.com/company/vistabylara",
    "https://www.behance.net/vistabylara",
    "https://ner.economy.ae/",
  ],
  twitterHandle: "@vistabylara",
  keywords: [
    "branding agency Dubai",
    "luxury web design UAE",
    "digital product design Dubai",
    "generative AI solutions UAE",
    "full stack development Dubai",
    "UX UI design agency UAE",
    "high-end website design Dubai",
    "premium branding agency GCC",
    "ecommerce development Dubai",
    "AI visibility Dubai",
    "GEO agency UAE",
    "AEO agency Dubai",
    "AI SEO Dubai",
    "SEO agency Dubai",
    "SEO company Dubai",
    "digital marketing company Dubai",
    "PPC agency Dubai",
    "technical SEO Dubai",
    "Claude SEO Dubai",
    "Bing Copilot SEO Dubai",
    "GEO services Dubai",
    "AEO services Dubai",
    "AI search optimization UAE",
    "digital marketing agency Dubai",
    "SEO services Dubai",
    "SEO agency Dubai",
    "SEO company Dubai",
    "SEO consultant Dubai",
    "technical SEO Dubai",
    "local SEO Dubai",
    "Arabic SEO Dubai",
    "Arabic SEO services",
    "Google Ads management Dubai",
    "Google Ads Dubai",
    "PPC agency Dubai",
    "Meta Ads Dubai",
    "Facebook Ads Dubai",
    "Instagram Ads Dubai",
    "Meta Pixel UAE",
    "Conversions API Dubai",
    "performance marketing Dubai",
    "content marketing strategy Dubai",
    "marketing automation UAE",
    "conversion rate optimization Dubai",
    "Shopify development agency Dubai",
    "Shopify agency Dubai",
    "Shopify SEO Dubai",
    "Shopify speed optimization Dubai",
    "e-commerce growth studio Dubai",
    "AI marketing agency Dubai",
    "AI SEO Dubai",
    "AI-powered SEO",
    "ChatGPT optimization",
    "Perplexity optimization",
    "Google AI Overviews optimization",
    "Google AI Overview optimization Dubai",
    "ChatGPT SEO Dubai",
    "Perplexity SEO Dubai",
    "Claude SEO Dubai",
    "Bing Copilot SEO Dubai",
    "Arabic SEO Dubai",
    "Local SEO Dubai",
    "HubSpot CRM Dubai",
    "lead generation Dubai",
    "mobile app development Dubai",
    "AI recommendation engine",
    "AI agent UAE",
    "AI agent Dubai",
    "real estate AI agent Dubai",
    "AI chatbot for real estate agents Dubai",
    "property lead generation UAE",
    "AI entity optimization",
    "AI schema markup",
    "AI citation building",
    "AI brand presence",
    "fashion marketing Dubai",
    "real estate marketing Dubai",
    "restaurant marketing Dubai",
    "clinic marketing Dubai",
    "B2B marketing Dubai",
    "sharikat SEO fi Dubai",
    "khadamat al tasweeq al raqmi Dubai",
    "tahsin muharrikat al bahth Dubai",
  ],
  ogImage: "/og-vista-ai-visibility.png",
} as const

export type SiteConfig = typeof siteConfig

export const whatsappLinks = {
  branding: "https://vista-wa-nurture.vistabylara.workers.dev/wa/branding",
  websites: "https://vista-wa-nurture.vistabylara.workers.dev/wa/websites",
  "digital-products": "https://vista-wa-nurture.vistabylara.workers.dev/wa/digital-products",
  development: "https://vista-wa-nurture.vistabylara.workers.dev/wa/development",
  "generative-ai": "https://vista-wa-nurture.vistabylara.workers.dev/wa/generative-ai",
  "uae-ai-agent": "https://vista-wa-nurture.vistabylara.workers.dev/wa/generative-ai",
  "google-ads-dubai": "https://vista-wa-nurture.vistabylara.workers.dev/wa/general",
  "meta-ads-dubai": "https://vista-wa-nurture.vistabylara.workers.dev/wa/general",
  general: "https://vista-wa-nurture.vistabylara.workers.dev/wa/general",
} as const

export type WhatsappLinkKey = keyof typeof whatsappLinks

export function getWhatsappLink(key?: string) {
  if (key && key in whatsappLinks) {
    return whatsappLinks[key as WhatsappLinkKey]
  }

  return whatsappLinks.general
}
